<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>javascript practise set </title>
</head>

<body>
    <script>
        // problem no 1

        // const loadscript = async (src) => {
        //     return new Promise((resolve, reject) => {
        //         let script = document.createElement("script")
        //         script.src = src
        //         script.onload = () => {
        //             resolve(src + " done success")
        //         }
        //         document.head.append(script)
        //     })
        // }
        // let a = loadscript("https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js")
        // a.then((value) => {
        //     console.log(value)
        // })

        // problem no 2

        // const loadscript = async (src) => {
        //     return new Promise((resolve, reject) => {
        //         let script = document.createElement("script")
        //         script.src = src
        //         script.onload = () => {
        //             resolve(src + " done success")
        //         }
        //         document.head.append(script)
        //     })
        // }
        // const main2 = async()=>{
        //     console.log(new Date().getMilliseconds())
        //     let a = await loadscript("https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js")
        //     console.log(a)
        //     console.log(new Date().getMilliseconds())
        // }
        // main2()

        // problem no 3
        // let p = () => {
        //     return new Promise((resolve, reject) => {
        //         setTimeout(() => {
        //             reject(new Error("please this is no acceptable"))
        //         }, 3000);
        //     })
        // }

        // let a = async () => {
        //     try {
        //         let c = await p()
        //         console.log(C)    
        //     } catch (error) {
        //         console.log("this error has been handlend")
        //     }
        //     console.log("the function is end")
        // }
        // a()

        // problem no 4

        let p1 = async () => {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve(10);
                }, 2000);
            })
        }
        let p2 = async () => {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve(20);
                }, 1000);
            })
        }
        let p3 = async () => {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve(30);
                }, 3000);
            })
        }


        const run = async () => {
            console.time("run")
            // let a1 = await p1() 
            // let a2 = await p2()
            // let a3 = await p3()

            let a1 = p1()
            let a2 = p2()
            let a3 = p3()
            
            let a1a2a3 = await Promise.all([a1, a2, a3])
            console.log(a1a2a3);
            // console.log(a3, a2, a1)
            console.timeEnd("run")
        }
        run()

    </script>
</body>

</html>